apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{APP_NAME}}-networkpolicy
  namespace: {{NAMESPACE}}
  labels:
    app: {{APP_NAME}}
spec:
  podSelector:
    matchLabels:
      app: {{APP_NAME}}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 80
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
