apiVersion: v1
kind: Secret
metadata:
  name: {{APP_NAME}}-tls
  namespace: {{NAMESPACE}}
  labels:
    app: {{APP_NAME}}
type: kubernetes.io/tls
data:
  tls.crt: {{TLS_CERT_BASE64}}
  tls.key: {{TLS_KEY_BASE64}}
