apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{APP_NAME}}
  namespace: argocd
  labels:
    app.kubernetes.io/name: {{APP_NAME}}
    app.kubernetes.io/managed-by: argocd
spec:
  project: {{PROJECT}}
  source:
    repoURL: {{REPO_URL}}
    targetRevision: {{BRANCH}}
    path: kustomize/{{APP_NAME}}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{NAMESPACE}}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
