apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  labels: { grafana_dashboard: "1" }
data:
  default-dashboard.json: |
{
  "annotations": {
    "list": []
  },
  "panels": [
    {
      "type": "graph",
      "title": "CPU Usage (node)",
      "targets": [
        {
          "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode='idle'}[5m])) * 100)"
        }
      ]
    }
  ],
  "schemaVersion": 36,
  "version": 1,
  "title": "Default"
}
