apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{APP_NAME}}-gateway
  namespace: {{NAMESPACE}}
  labels:
    app: {{APP_NAME}}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "{{APP_NAME}}.example.com"
