apiVersion: v1
kind: Secret
metadata:
  name: {{APP_NAME}}-secret
  namespace: {{NAMESPACE}}
  labels:
    app: {{APP_NAME}}
type: Opaque
data:
  DB_USER: ZGJfdXNlcg==         # base64("db_user")
  DB_PASSWORD: ZGJfcGFzcw==     # base64("db_pass")
