apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{PROJECT}}
  namespace: argocd
  labels:
    env: dev
    app.kubernetes.io/part-of: argocd
spec:
  description: "Development environment"
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
