replicaCount: {{REPLICAS}}

image:
  repository: {{IMAGE}}
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: {{PORT}}

resources: {}
# Optional - added only if selected
# resources:
#   limits:
#     cpu: 200m
#     memory: 512Mi
#   requests:
#     cpu: 100m
#     memory: 256Mi

probes: {}
# Optional - added only if selected
# probes:
#   liveness:
#     path: /
#     port: {{PORT}}
#   readiness:
#     path: /
#     port: {{PORT}}

env: []
# Optional - added only if selected
# env:
#   - name: ENV
#     value: production
