#!/bin/bash
REPO_URL="https://raw.githubusercontent.com/InfraForgeLabs/InfraForge/main/SecurityTemplates"
OUT_DIR="generated"
CACHE_DIR=".cache/security-templates"
mkdir -p "$OUT_DIR" "$CACHE_DIR"

VERSION="v2.1"
DATE=$(date +"%Y-%m-%d %H:%M:%S")

DEFAULT_MODE="2"
DEFAULT_APP="shieldops-demo"
DEFAULT_IMAGE="nginx:latest"
DEFAULT_TARGET="http://example.com"
DEFAULT_ADDONS="1,2"

timestamp() { date +"%H:%M:%S"; }
info()    { echo -e "\033[1;34m[$(timestamp)] $1\033[0m"; }
success() { echo -e "\033[1;32m[$(timestamp)] $1\033[0m"; }
warn()    { echo -e "\033[1;33m[$(timestamp)] $1\033[0m"; }
error()   { echo -e "\033[1;31m[$(timestamp)] $1\033[0m"; }

# --- Online Detection ---
CHECK_URL="$REPO_URL/sast/sonar-project.properties"
if curl -sfI "$CHECK_URL" >/dev/null 2>&1; then
  ONLINE=true
  success "🌐 Online mode detected — templates will be fetched from GitHub."
else
  ONLINE=false
  warn "⚠️ Offline mode — using cached or local templates."
fi

# --- CLI Argument Parsing ---
while [[ "$#" -gt 0 ]]; do
  case $1 in
    --mode) mode="$2"; shift ;;
    --app) app="$2"; shift ;;
    --image) image="$2"; shift ;;
    --target) target="$2"; shift ;;
    --addons) addons="$2"; shift ;;
    --bundle) BUNDLE="true" ;;
    --ci) CI_MODE="true" ;;
    --auto) AUTO="true" ;;
    --help|-h)
      echo "============================================================"
      echo "🛡️ Security Template Generator $VERSION — Help & Usage"
      echo "============================================================"
      echo "Usage: bash security-template.sh [options]"
      echo "  --mode <1-5>           1=SAST, 2=SCA, 3=DAST, 4=Secrets, 5=Policy"
      echo "  --bundle               Generate all modules"
      echo "  --ci                   Add CI/CD pipelines"
      echo "  --auto                 Non-interactive automation mode"
      echo "============================================================"
      exit 0 ;;
    *) ;;
  esac
  shift
done

echo "============================================"
info " 🛡️ Universal Security Template Generator $VERSION"
echo "============================================"

# --- Interactive Mode (Editable + Multi-select) ---
if [ -z "$mode" ] && [ "$BUNDLE" != "true" ] && [ "$AUTO" != "true" ]; then
  echo "Select security templates to generate (comma-separated, e.g. 1,3,5):"
  echo "1) SAST (SonarQube, Semgrep)"
  echo "2) SCA (Trivy, Grype)"
  echo "3) DAST (OWASP ZAP)"
  echo "4) Secrets (Gitleaks)"
  echo "5) Policy (OPA, Conftest)"
  read -e -p "Your choice [Default: $DEFAULT_MODE]: " mode
  mode=${mode:-$DEFAULT_MODE}
fi

if [ "$BUNDLE" == "true" ]; then
  MODES="1,2,3,4,5"
else
  MODES=$mode
fi

if [ -z "$app" ]; then
  if [ "$AUTO" != "true" ]; then
    read -e -p "Enter project name [Default: $DEFAULT_APP]: " app
  fi
fi
app=${app:-$DEFAULT_APP}

if [ -z "$image" ]; then
  if [ "$AUTO" != "true" ]; then
    read -e -p "Enter container image [Default: $DEFAULT_IMAGE]: " image
  fi
fi
image=${image:-$DEFAULT_IMAGE}

if [ -z "$target" ]; then
  if [ "$AUTO" != "true" ]; then
    read -e -p "Enter target URL (for ZAP scans) [Default: $DEFAULT_TARGET]: " target
  fi
fi
target=${target:-$DEFAULT_TARGET}

DEST_DIR="$OUT_DIR/$app"
mkdir -p "$DEST_DIR"

# --- Template Mapping ---
declare -A FILES
FILES=( 
  ["sast"]="sonar-project.properties semgrep.yml"
  ["sca"]="trivy-ci.yml grype.yml"
  ["dast"]="zap-config.yaml"
  ["secrets"]="gitleaks.toml"
  ["policy"]="opa-policy.rego conftest-policy.yaml"
)

# --- Fetch Template Function ---
fetch_template() {
  local rel="$1"
  local dest="$2"
  local cache="$CACHE_DIR/$(basename "$rel")"
  mkdir -p "$(dirname "$dest")"

  if [ "$ONLINE" = true ] && curl -sf --retry 3 --retry-delay 2 "$REPO_URL/$rel" -o "$dest"; then
    cp "$dest" "$cache" >/dev/null 2>&1
    success "✅ Downloaded $rel"
  elif [ -f "$cache" ]; then
    cp "$cache" "$dest"; success "📦 Used cached: $(basename "$cache")"
  elif [ -f "$rel" ]; then
    cp "$rel" "$dest"; warn "📂 Used local fallback: $rel"
  else
    warn "⚠️ Missing template: $rel"
  fi
}

inject_placeholders() {
  local file="$1"
  sed -i \
    -e "s/{{APP_NAME}}/$app/g" \
    -e "s/{{IMAGE}}/$image/g" \
    -e "s|{{TARGET_URL}}|$target|g" \
    -e "s/{{DATE}}/$DATE/g" \
    -e "s/{{VERSION}}/$VERSION/g" "$file"
}

prepend_metadata() {
  local file="$1"
  sed -i "1i# ============================================================\n# Generated by Security Template Generator $VERSION\n# App: $app | Date: $DATE\n# ============================================================\n" "$file"
}

generate_mode_templates() {
  local mode_path="$1"
  for file in ${FILES[$mode_path]}; do
    DEST="$DEST_DIR/$file"
    fetch_template "$mode_path/$file" "$DEST"
    inject_placeholders "$DEST"
    prepend_metadata "$DEST"
  done
}

# --- Multi-select Generation ---
IFS=',' read -ra SELECTED <<< "$MODES"
for m in "${SELECTED[@]}"; do
  case ${m// /} in
    1) MODE_PATH="sast" ;;
    2) MODE_PATH="sca" ;;
    3) MODE_PATH="dast" ;;
    4) MODE_PATH="secrets" ;;
    5) MODE_PATH="policy" ;;
    *) continue ;;
  esac
  info "📁 Generating templates for: $MODE_PATH"
  generate_mode_templates "$MODE_PATH"
done

# --- Addons ---
echo "--------------------------------------------"
echo "Available Addons: 1) Slack  2) Email  3) Jira"
if [ -z "$addons" ] && [ "$AUTO" != "true" ]; then
  read -e -p "Select addons (comma-separated, Default: $DEFAULT_ADDONS): " addons
fi
addons=${addons:-$DEFAULT_ADDONS}

IFS=',' read -ra ADDONS <<< "$addons"
for addon in "${ADDONS[@]}"; do
  case ${addon// /} in
    1) addon_path="slack-alert.yaml" ;;
    2) addon_path="email-alert.yaml" ;;
    3) addon_path="jira-integration.yaml" ;;
    *) continue ;;
  esac
  info "📦 Adding addon: $addon_path"
  CACHE_FILE="$CACHE_DIR/$addon_path"
  if [ "$ONLINE" = true ] && curl -sf "$REPO_URL/addons/$addon_path" -o "$DEST_DIR/$addon_path"; then
    cp "$DEST_DIR/$addon_path" "$CACHE_FILE" >/dev/null 2>&1
    success "✅ Added from GitHub"
  elif [ -f "$CACHE_FILE" ]; then
    cp "$CACHE_FILE" "$DEST_DIR/$addon_path"; success "📦 Added from cache"
  else
    warn "⚠️ Skipped missing addon $addon_path"
  fi
  inject_placeholders "$DEST_DIR/$addon_path"
  prepend_metadata "$DEST_DIR/$addon_path"
done

# --- CI/CD Integration ---
if [ "$CI_MODE" == "true" ]; then
  info "⚙️ Adding CI/CD security pipelines..."
  mkdir -p "$DEST_DIR/ci"
  fetch_template "ci/security-pipeline.yml" "$DEST_DIR/ci/security-pipeline.yml"
  fetch_template "ci/Jenkinsfile" "$DEST_DIR/ci/Jenkinsfile"
  inject_placeholders "$DEST_DIR/ci/security-pipeline.yml"
  inject_placeholders "$DEST_DIR/ci/Jenkinsfile"
  success "✅ CI/CD pipelines added under $DEST_DIR/ci/"
fi

# --- Version Record ---
echo "Security Template $VERSION | Generated on $DATE" > "$DEST_DIR/.version"

# --- Output ---
success "✅ Security templates generated successfully: $DEST_DIR"
( command -v tree >/dev/null 2>&1 && tree "$DEST_DIR" ) || ls -R "$DEST_DIR"

# --- Summary ---
echo "--------------------------------------------"
info "📊 Summary of Generated Artifacts:"
for m in "${SELECTED[@]}"; do
  case ${m// /} in
    1) name="SAST" ;;
    2) name="SCA" ;;
    3) name="DAST" ;;
    4) name="Secrets" ;;
    5) name="Policy" ;;
  esac
  echo " - $name templates generated."
done
echo " Addons: $addons"
[[ "$CI_MODE" == "true" ]] && echo " CI/CD: Enabled"
[[ "$BUNDLE" == "true" ]] && echo " Mode: Bundle (Full Suite)"
echo " Version: $VERSION"
echo " Generated: $DATE"
echo "--------------------------------------------"
