apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{APP_NAME}}-dr
  namespace: {{NAMESPACE}}
spec:
  host: {{APP_NAME}}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 100
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 5s
      baseEjectionTime: 15s
      maxEjectionPercent: 50
